name: Build and Release React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          

      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=7.3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.10.0' # Use the specific Node.js version required by your React Native project

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Node.js modules using Yarn
        run: yarn install

      - name: Build and Test
        run: ./gradlew clean build

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.zip
          asset_name: app-release.zip
          asset_content_type: application/zip
