name: Build and Release React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check ls
        run: ls -la

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.10.0'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Node.js modules using Yarn
        run: yarn install
          
      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=6.4.1

      - name: Remove Start remove [index.android.bundle]
        run: rm app/src/main/assets/index.android.bundle
      
      - name: Start bundle assets
        run: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      
      - name: Start remove res/drawable*
        run: rm -rf android/app/src/main/res/drawable-hdpi android/app/src/main/res/drawable-mdpi android/app/src/main/res/drawable-xhdpi android/app/src/main/res/drawable-xxhdpi android/app/src/main/res/drawable-xxxhdpi android/app/src/main/res/raw || true

      - name: Clean Gradle
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{github.workspace}}/android/app/release/app-release.apk
          retention-days: 30
          if-no-files-found: error

  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release
      - name: Achive artifact
        uses: thedoctor0/zip-release@master
        with:
          filename: app-release.zip

      - name: Create github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-release.zip
          asset_name: app-release.zip
          asset_content_type: application/zip